object Form7: TForm7
  Left = 462
  Top = 338
  Width = 305
  Height = 264
  Caption = 'Lehrer Bearbeiten/L'#246'schen'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 8
    Top = 43
    Width = 129
    Height = 25
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Name:'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label2: TLabel
    Left = 8
    Top = 75
    Width = 129
    Height = 25
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Vorname:'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label3: TLabel
    Left = 8
    Top = 107
    Width = 129
    Height = 25
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Amtsbez.:'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label4: TLabel
    Left = 8
    Top = 139
    Width = 129
    Height = 25
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Geburtsdatum:'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label5: TLabel
    Left = 8
    Top = 11
    Width = 129
    Height = 25
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Lehrerauswahl:'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object CB_Admin: TCheckBox
    Left = 144
    Top = 168
    Width = 145
    Height = 25
    Caption = 'Adminrechte'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 0
  end
  object ED_Name: TEdit
    Left = 144
    Top = 40
    Width = 145
    Height = 27
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
  end
  object ED_vorname: TEdit
    Left = 144
    Top = 72
    Width = 145
    Height = 27
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 2
  end
  object Ed_Amts: TEdit
    Left = 144
    Top = 104
    Width = 145
    Height = 27
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 3
  end
  object ED_geb: TEdit
    Left = 144
    Top = 136
    Width = 145
    Height = 27
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 4
  end
  object B_save: TButton
    Left = 144
    Top = 200
    Width = 145
    Height = 25
    Caption = 'Speichern'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 5
    OnClick = B_saveClick
  end
  object B_delete: TButton
    Left = 8
    Top = 200
    Width = 129
    Height = 25
    Caption = 'Lehrer l'#246'schen'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 6
    OnClick = B_deleteClick
  end
  object CB_Lehrer: TComboBox
    Left = 144
    Top = 8
    Width = 145
    Height = 27
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ItemHeight = 19
    ParentFont = False
    TabOrder = 7
    Text = 'CB_Lehrer'
    Visible = False
    OnChange = CB_LehrerChange
  end
end
